# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Why Do You Care?!
email: moyer.will@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A podcast about the media we love, the media we hate, and why we care.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://whydoyoucare.fm" # the base hostname & protocol for your site
lang: en-US

# Build settings
markdown: kramdown
permalink: :title

# Global vars
kt_url: https://twitter.com/kingdomhorse
will_url: https://twitter.com/willmoyer