# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brain Gravy with Ryan Heckman 
email: ryanheckman@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Stand up comedian Ryan Heckman discusses anything and everything.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://braingravy.org" # the base hostname & protocol for your site
lang: en-US

# Build settings
markdown: kramdown
permalink: :title

# Global vars
ryan_url: https://twitter.com/rynoctopus
